### ISSUE TITLE
ScreenOff option instead of shutdown (2012-2014TVs)

### ISSUE THREAD

**Issue by corrpel** [filimonic/Kodi.Screensaver.TurnOffLGTV#3]
I was looking for this for so long!! Thank you very much for bringing this together. I have an idea for improving, not sure if it can be implemented.
It would be great if we would have an option for "Screen off" feature. currently, you have to access menu tv to set the screen to "screen off" in power saving option. It would be awesome if an option for just powering off the screen but keep the tv on would be present (music lovers).

**Comment by filimonic** [comment]
There is no way to turn off only screen part (lcd panel or backlight) of
your tv as far as I know. Sorry.
11 янв. 2016 г. 11:29 пользователь "corrpel" notifications@github.com
написал:

**Comment by corrpel** [comment]
Thanks for reply. This is a 2012 TV. 42lm620s. I know this option is
present in newer devices. Also, i had a look in the lg smart app, but no
option for this. Do you think if i request an option in the app for
screenoff it will be doable? As a feedback, your script is awesome for me,
because i don't us another source other than a raspberry pi. If another
source is used, when you switch to kodi and the screensaver was activated,
the TV will power off and you need to power on back. Thank you for your
work!

**Comment by filimonic** [comment]
Do not think it is possible for me. I do not have access to LGs internal
docs and on both my tvs (2012 or 2015) i can not find such thing. Can you
tell me more about this feature?
11 янв. 2016 г. 20:49 пользователь "corrpel" notifications@github.com
написал:

**Comment by corrpel** [comment]
well, on a 2012 LG TV you can access it two ways. One is by going in
"Settings" on keyboard, access first tab on the left (where you have the
video options for adjusting display saturation, brightness, etc) The first
option here is "Energy saver" and you have more options: Minimum, Medium,
Screen off. The other option is to press "q.menu" under the blue key. and
then navigate to energy saver, where you have the same options. Thanks for
prompt response ;) If i use screen off, the display will switch off but the
audio will keep going, only the display is black like it was in power off
state.

**Comment by filimonic** [comment]
Okay， will try to look forward for this feature this week and will tell you
something about possibilities or impossibilities or something else
11 янв. 2016 г. 21:00 пользователь "corrpel" notifications@github.com
написал:

> well, on a 2012 LG TV you can access it two ways. One is by going in
> "Settings" on keyboard, access first tab on the left (where you have the
> video options for adjusting display saturation, brightness, etc) The first
> option here is "Energy saver" and you have more options: Minimum, Medium,
> Screen off. The other option is to press "q.menu" under the blue key. and
> then navigate to energy saver, where you have the same options. Thanks for
> prompt response ;) If i use screen off, the display will switch off but the
> audio will keep going, only the display is black like it was in power off
> state.
> 
> On Mon, Jan 11, 2016 at 7:51 PM, Alexey D. Filimonov <

**Comment by corrpel** [comment]
not sure if you see the screenshots, but here are some more

**Comment by filimonic** [comment]
Oh. I am replying using mail so I dont see any. Will check them later，
sorry:-)
11 янв. 2016 г. 21:05 пользователь "corrpel" notifications@github.com
написал:

> not sure if you see the screenshots, but here are some more
>

**Comment by corrpel** [comment]
thank you very much!

**Comment by filimonic** [comment]
I found it can be done for 2012-2014 TVs only by simulating key pressing. BUT because script does not know what is your settings (the current position of menu), you should specify number of keypresses.
Like that: 
409,12,12,12,20 (means "Energy saving menu, Up, Up, Up, OK")

For 2015 i did not found it

Will try to make it soon

**Comment by corrpel** [comment]
That is awesome news. We are waiting for the updated script ;). Good job!

**Comment by corrpel** [comment]
@filimonic hei man how are you? Any update on this will be appreciated. Thanks.

**Comment by filimonic** [comment]
@corrpel Please take a look at [This release](https://github.com/filimonic/Kodi.Screensaver.TurnOffLGTV/releases/tag/v1.1.5)

It is made for 2014 TVs only.
If the music is playing now and the setting in screensaver settings is set, addon will simulate keypresses: 
- Push EnergySaving Menu (there is a hotkey for it in LG TVs)
- Push "Down" several times (you need to set up how many)
- Push OK

**Comment by corrpel** [comment]
@filimonic thank you very much it is working!
Some feedback on this for your final release:
1. Remove the message when you come back when energy saving is used.
2. Add "Go to energy saving instead of shutdown" and keep also the music option (much appreciated your work).
3. Execute the script only if KODI is the active source (CEC-Signaling). The TV is switched off even if another source is used (like TV).
4. I wish more people with LG TVs can see this addon:))

And to add something, the TV did not go into energy saving when the status music is used (the screen with the low bar and song name - when you press back from the main menu and the music is playing) I'll update if i notice something new.

Thanks!

**Comment by filimonic** [comment]
@corrpel 
1. Hope this can be done, but not sure
2. Ok
3. Can not find if Kodi have such function. So can not check if Kodi is active source. I think it needs CEC developement. According to [This](http://mirrors.kodi.tv/docs/python-docs/15.x-isengard/) and [This](http://kodi.wiki/view/List_of_built-in_functions), there is no option to "check" if Kodi is active source.
