### ISSUE TITLE
Possibility of not activating screen saver after XX mins?

### ISSUE THREAD

**Issue by chearmstrong** [filimonic/Kodi.Screensaver.TurnOffLGTV#5]
Hi,

I'm triggering the screen saver to power off my TV via the Kodi RPC JSON API - it seems to work well.

However, there are time when Kodi (running on my Pi) is on, but I am watching something on regular TV (another TV source). I had set the screen saver time to 16 mins, but it turns off the TV when it hits that - I don't want it to.

Is it possible to trigger the screensaver/TV off event only using the JSON API, and not have the screen saver activate after 60 mins?

**Comment by filimonic** [comment]
I do not know how to let Kodi know that you are using HDMI source different from raspberry's one. It IS possible to do via CEC afaik, but Kodi's api does not provide any method doing this. Sorry. Have the same problem sometimes.
