### ISSUE TITLE
Any idea if this could work with Samsung TV?

### ISSUE THREAD

**Issue by Ingvix** [filimonic/Kodi.Screensaver.TurnOffLGTV#9]
Everything else works with cec expect turning the TV off when screensaver activates. Is this solely for LG or could this work on others too? If former would it be a hard job to make this work for Samsung TV's too?

**Comment by Ingvix** [comment]
I learned it was a bug that prevent from the Kodi's native standby function to work and not the TV's fault. The bug was easily fixed and no need for this issue anymore.

**Comment by filimonic** [comment]
BTW according to [libCEC compatibility page](http://libcec.pulse-eight.com/Vendor/Support) Samsung TVs work OK, but you possibly need to enable `Auto-Standby` in Anynet+ settings

**Comment by Ingvix** [comment]
Nah, it was just Debian's old Kodi build that had a bug with the GUI settings and I had to change a value from file. I wish I had elaborated how I did it for others with the same problem but can't remember the specifics anymore and too lazy to look into again.
